pathway_list: null  # pathway_constraints is ignored if non-null
pathway_constraints:
    min_pathway_node_size: 5
    max_pathway_edge_size: 1000

studies:
    - epistasis
    - main

databases:
    - kegg
    - biocarta
    - nci
    - panther
    - pharmgkb
