workdir: pipeline_run

databases:
    - kegg
    - biocarta
    - nci
    - panther
    - pharmgkb

cases:
    - [epistasis, ATF6, hsa04141]
    - [epistasis, ERN1, hsa04210]
    - [epistasis, ERN1, hsa04141]
    - [epistasis, EIF2AK3, hsa04210]
    - [epistasis, EIF2AK3, hsa04141]
    - [epistasis, "ATF6,EIF2AK3", hsa04141]
    - [main, EIF2S1, hsa04141]
